name: geraldKlein
favicon: null
layout_spectrum: 0.8207599935121834
typography_spectrum: 0.342369087273255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0027511564549058676
  lightness: 0.615069545339793
  saturation: 0.6502655802760273
  rhythmicContrast: 0.23614053754135966
purpose: []
